{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openldes-server.fullname" . }}-postgres
  labels:
    {{- include "openldes-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgres.port | default 5432 }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "openldes-server.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
{{- end }}

