# Override the default values for the ldio Helm chart here.
config:
  orchestrator:
    directory: /ldio/pipelines
    pipelines:
      - name: occupancy-pipeline
        description: "Polls for JSON public parking occupancy data, converts to linked data, creates versions & sends to LDES server."
        input:
          name: Ldio:HttpInPoller
          config:
            url: https://data.stad.gent/api/explore/v2.1/catalog/datasets/bezetting-parkeergarages-real-time/exports/json?lang=en&timezone=Europe%2FBrussels
            cron: "0 */1 * * * *"
          adapter:
            name: Ldio:JsonToLdAdapter
            config:
              context: |
                {
                  "@context": {
                    "@vocab": "https://example.org/ns/mobility#",
                    "urllinkaddress": "@id",
                    "type": "@type",
                    "lastupdate": {
                      "@type": "http://www.w3.org/2001/XMLSchema#dateTime"
                    }
                  }
                }
        outputs:
          - name: Ldio:ConsoleOut
          - name: Ldio:HttpOut
            config:
              endpoint: http://ldes-openldes-server.openldes-server.svc.cluster.local:8080/occupancy
              rdf-writer:
                content-type: text/turtle
  extraConfig:
    server:
      port: 8080
    logging:
      level:
        root: WARN
        org.openldes: INFO

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 8080
